# Generated by Django 5.1.7 on 2025-03-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
